# Generated by Django 2.2 on 2019-05-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('kr_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='snumap.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('operating_hours', models.TextField()),
                ('info', models.TextField()),
                ('edges', models.ManyToManyField(related_name='shuttles', to='snumap.Edge')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('talker', models.TextField()),
                ('description', models.TextField()),
                ('where', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminars', to='snumap.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('edges', models.ManyToManyField(to='snumap.Edge')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_for', to='snumap.Spot')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_for', to='snumap.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('kr_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('operating_hours', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='snumap.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='snumap.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('time', models.CharField(max_length=200)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='snumap.Building')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='spots',
            field=models.ManyToManyField(related_name='edges', to='snumap.Spot'),
        ),
        migrations.AddField(
            model_name='building',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='snumap.Spot'),
        ),
    ]
